### ISSUE TITLE
JS error in jupyter notebook (but working in lab)

### ISSUE THREAD

**Issue by johnhw** [space928/Shaders-For-Scientific-Visualisation#31]
Problem: In Jupyter Notebook 6.5.4 on Windows/Chrome, attempting to `canvas.run()` causes a Javascript error, apparently due to a missing resource. The same install works correctly in `jupyter lab`

I have run 

```
jupyter nbextension install --sys-prefix --overwrite --py pySSV
jupyter nbextension enable --sys-prefix --py pySSV
```

and  the extension seems to be installed okay. `ipywidgets` is installed okay, and I have run 
```
jupyter nbextension enable --py widgetsnbextension --sys-prefix
```

console output:
```
:8888/static/@jupyter-widgets/base.js?v=20240116162726:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
Untitled.ipynb:1 Refused to execute script from 'http://localhost:8888/static/@jupyter-widgets/base.js?v=20240116162726' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
utils.js:62 Failed to load extension: Array(1) Error: Script error for "@jupyter-widgets/base", needed by: nbextensions/py-ssv/index
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:168:17)
    at HTMLScriptElement.onScriptError (require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:1735:36)
(anonymous) @ utils.js:62
utils.js:37 Loading extension: jupyter-js-widgets/extension
:8888/nbextensions/widgets/notebook/js/extension.js?v=20240116162726:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
Untitled.ipynb:1 Refused to execute script from 'http://localhost:8888/nbextensions/widgets/notebook/js/extension.js?v=20240116162726' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
main.js:240 Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
(anonymous) @ main.js:240
kernel.js:107 Kernel: kernel_connected (7ace92e9-9299-4149-8ef1-de6344ccbf5d)
kernel.js:107 Kernel: kernel_ready (7ace92e9-9299-4149-8ef1-de6344ccbf5d)
manager-base.js:291 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early
_loadFromKernel @ manager-base.js:291
clipboard.js:61 Clipboard types: text/plain
:8888/static/py-ssv.js?v=20240116162726:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
Untitled.ipynb:1 Refused to execute script from 'http://localhost:8888/static/py-ssv.js?v=20240116162726' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
manager-base.js:575 Error: Script error for "py-ssv"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:168:17)
    at HTMLScriptElement.onScriptError (require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:1735:36)
```

**Comment by space928** [comment]
I just checked and it seems to work fine in Jupyter Notebook 7.0.7. Is there a particular use case that necessitates Jupyter Notebook 6?

**Comment by johnhw** [comment]
No - confirmed working in Notebook 7; closing.
